apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geotax.fullname" . }}
  labels:
    service: precisely
    app: {{ include "geotax.fullname" . }}
    {{- include "geotax.labels" . | nindent 4 }}
  {{- if .Values.global.manualDataConfig.enabled }}
  annotations:
    precisely.com/config-checksum: {{ .Values.global.manualDataConfig.configMapData | toYaml | sha256sum }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: precisely
      app: {{ include "geotax.fullname" . }}
      {{- include "geotax.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        service: precisely
        app: {{ include "geotax.fullname" . }}
        {{- include "geotax.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geotax.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "geotax-svc.volumeMounts" . | nindent 12 }}
          env:
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geotax-data-config.name" . }}
                  key: geotax.vintage
            - name: SDK_BLOCKING_THREADS
              value: "24"
            - name: SDK_BLOCKING_QUEUE_CAPACITY
              value: "100000"
            - name: SDK_POOL_MAX_TOTAL
              value: "8"
            - name: SDK_POOL_MAX_TOTAL_PER_KEY
              value: "2"
            - name: SDK_POOL_MAX_IDLE_PER_KEY
              value: "2"
            - name: AUTH_ENABLED
              value: "false"
            - name: KAFKA_ENABLED
              value: "false"
            - name: IS_HELM_SOLUTION
              value: "true"
      {{- if .Values.global.syncDataConfig.enabled }}
      initContainers:
        - name: {{ printf "%s-%s" .Chart.Name "reference-data" }}
          image: peterdavehello/azcopy:latest
          command:
            - sh
            - -c
            - mkdir -p ${AZURE_STORAGE_DATA_PATH} && time azcopy sync "https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_STORAGE_CONTAINER_NAME}?${AZURE_SAS_TOKEN}" ${AZURE_STORAGE_DATA_PATH} --recursive && echo Reference Data Download Completed Successfully.
          volumeMounts:
            {{- include "geotax-svc.volumeMounts" . | nindent 12 }}
          env:
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: {{ .Values.global.nfs.containerName }}
            - name: AZURE_STORAGE_DATA_PATH
              value: {{ index .Values.global.manualDataConfig.configMapData "geotax.vintage" }}
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: {{ .Values.global.nfs.storageAccount }}
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: "azure_sas_token"
                  name: {{ include "geotax-azure-secret.name" . }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if not .Values.global.syncDataConfig.enabled }}
        - name: geotax-host-volume
          persistentVolumeClaim:
            claimName: {{ include "geotax-pvc.name" . }}
        {{- end }}
        {{- if .Values.global.syncDataConfig.enabled }}
        - name: geotax-host-volume
          hostPath:
            path: {{ .Values.global.nfs.volumeMountPath }}
            type: DirectoryOrCreate
        {{- end }}