apiVersion: v1
kind: Service
metadata:
  name: {{ include "geotax.fullname" . }}
  labels:
    {{- include "geotax.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geotax.selectorLabels" . | nindent 4 }}
