kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "geotax-storage-class.name" . }}
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "geotax-pv.name" . }}
  finalizers: [ ]
  labels:
    {{- include "geotax-pvc.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "geotax-storage-class.name" . }}
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.nfs.fileSystemId }}.efs.{{ .Values.global.awsRegion }}.amazonaws.com
    volumeAttributes:
      path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geotax-pvc.name" . }}
  finalizers: [ ]
  labels:
    {{- include "geotax-pvc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "geotax-storage-class.name" . }}
  volumeName: {{ include "geotax-pv.name" . }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G