apiVersion: v2
name: geotax-application
description: A Helm chart for Geo Tax Application Service

type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: geotax-hook
    repository: file://charts/geotax-hook
    version: "1.0.0"
    condition: geotax-hook.enabled