global:
  nfs:
    # The NFS path
    # You can get this by running following command:
    # gcloud filestore instances describe {fileStoreName} --zone us-east1-c --format="value(fileShares[0].name)"
    path: /geotax_data
    # The server url for NFS
    # You can get this by running below command:
    # gcloud filestore instances describe {fileStoreName} --zone us-east1-c --format="value(networks[0].ipAddresses[0])"
    server: fileStoreServerIP
  pdxApiKey: "<your-PDX-API-key>"
  pdxSecret: "<your-PDX-API-secret>"
  #
  # Overwrite this value if you want to install only a specific data.
  # The value should always be provided as escaped JSON
  dataConfigMap: "[\"Vertex L-Series ASCII#United States#All USA#Spectrum Platform Data\",\"Payroll Tax Data#United States#All USA#Spectrum Platform Data\",\"Tax Rate Data ASCII#United States#All USA#Spectrum Platform Data\",\"Sovos Correspondence File ASCII#United States#All USA#Spectrum Platform Data\",\"Vertex O-Series ASCII#United States#All USA#Spectrum Platform Data\",\"GeoTAX Auxiliary File ASCII#United States#All USA#Spectrum Platform Data\",\"GeoTAX Premium Masterfile Monthly#United States#All USA#Spectrum Platform Data\",\"Vertex Q-Series ASCII#United States#All USA#Spectrum Platform Data\",\"Insurance Premium Tax Data#United States#All USA#Spectrum Platform Data\",\"Special Purpose District Data#United States#All USA#Spectrum Platform Data\"]"

geotax-reference-data:
  dataDownload:
    image:
      repository: geotax-reference-data-extractor
      tag: 3.0.1