global:
  nfs:
    # The NFS path
    # You can get this by running following command:
    # gcloud filestore instances describe {fileStoreName} --zone us-east1-c --format="value(fileShares[0].name)"
    path: /geotax_data
    # The server url for NFS
    # You can get this by running below command:
    # gcloud filestore instances describe {fileStoreName} --zone us-east1-c --format="value(networks[0].ipAddresses[0])"
    server: fileStoreServerIP