dataDownload:
  enabled: true
  image:
    repository: ~
    pullPolicy: Always
    tag: ~
    pullSecrets: [ ]

nameOverride: "geotax-reference-data"
fullnameOverride: "geotax-reference-data"

service:
  type: ClusterIP
  port: 80

nodeSelector: { }

global:
  pdxApiKey: ~
  pdxSecret: ~
  nfs:
    volumeMountPath: "/mnt/data/geotax-data"
    geotaxBasePath: "geotax"
  dataConfigMap: ~