{{- if .Values.geotax.global.syncDataConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geotax-azure-secret.name" . }}
  labels:
    {{- include "geotax-azure-secret.labels" . | nindent 4 }}
data:
  azure_sas_token: {{ required "A SAS Token is required for granting limited access to Azure Storage resources using shared access signatures (SAS). Follow https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview for more information!" .Values.global.nfs.sasToken | b64enc }}
{{- end}}