version: "3.9"
services:
  precisely-geotax-svc:
    image: ${_GEOTAX_IMAGE:-geotax-service:3.0.2}
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G
    ports:
      - "${_SERVICE_PORT:-8080}:8080"
    volumes:
      - ${_DATA_PATH:-/data/extracted}:/mnt/data/extracted
    environment:
      - DATA_PATH=/mnt/data/extracted
      - AUTH_ENABLED=false
      - METRICS_ENABLED=true
    networks:
      - precisely-geotax
    restart: always
networks:
  precisely-geotax:
    name: geotax